### ISSUE TITLE
Complete History Micro App

### ISSUE THREAD

**Issue by mouimet-infinisoft** [mouimet-infinisoft/steve#41]
I converted History Compoenent into a micro federated app. It will be reuse much more easily. I have scoped and defined a contract so it is stateless.

Look at following link for contract

https://github.com/mouimet-infinisoft/steve/tree/dev/apps/micro/history#history-microapps

You can start the app within its directory  `apps/micro/history`

```sh
$  npm run start:module
```
Use this branch
Be sure it is sync with dev!

![image](https://user-images.githubusercontent.com/47437825/180704967-f7705bd5-8bd6-48b0-b15e-c9901389bb94.png)

**Comment by Jaal-tech** [comment]
- History Timeline is already added by @mouimet-infinisoft -- Fully Open ended for props. 
- History Details basic open ended added for further implementation
- Scroll Tested with Mock but scroller will be wrapped around container of this component. 
- Empty Component Default Added to Contract
